# Generated by Django 3.2.22 on 2023-11-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231111_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size_l_stock',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_m_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_s_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_xl_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_xs_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='Medium', max_length=10),
        ),
    ]
